#!/usr/bin/env bash
# DeviceManager client setup (Docker). Initialises prerequisites on THIS host,
# then starts the client with docker compose:
#   - writes .env (HOST_URL + API_KEY)
#   - auto-enables the Tailscale socket mount only if Tailscale is running here
#   - optionally authorizes the dashboard's SSH key (in-browser terminal)
#   - docker compose up -d --build
#
# Run from the client/ directory:  sudo ./install.sh
# (sudo is needed only if you enable SSH provisioning; plain docker access
#  otherwise. Non-interactive: HOST_URL=... API_KEY=... ENABLE_SSH=y SSH_USER=root)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"

# --- prereq: Docker + Compose v2 ---
if ! command -v docker >/dev/null 2>&1; then
  echo "Docker is not installed. Install Docker, or use ./install-native.sh for a non-Docker box." >&2
  exit 1
fi
if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose v2 is required (the 'docker compose' subcommand)." >&2
  exit 1
fi

# --- prereq: .env ---
if [[ -f .env ]]; then
  echo ".env already exists — leaving it as-is."
  HOST_URL="$(grep -E '^HOST_URL=' .env | cut -d= -f2- || true)"
else
  HOST_URL="${HOST_URL:-}"
  API_KEY="${API_KEY:-}"
  if [[ -z "${HOST_URL}" ]]; then
    echo "Enter the DeviceManager host URL, including the port. e.g. http://192.168.50.225:8000"
    read -rp "Host URL: " HOST_URL
  fi
  if [[ -z "${API_KEY}" ]]; then
    read -rp "API key for this device (from the dashboard): " API_KEY
  fi
  if [[ -z "${HOST_URL}" || -z "${API_KEY}" ]]; then
    echo "HOST_URL and API_KEY are both required. Aborting." >&2
    exit 1
  fi
  HOST_URL="${HOST_URL%/}"
  [[ "${HOST_URL}" == http://* || "${HOST_URL}" == https://* ]] || HOST_URL="http://${HOST_URL}"
  cat > .env <<EOF
HOST_URL=${HOST_URL}
API_KEY=${API_KEY}
REPORT_INTERVAL=60
SSH_LOG_WINDOW_MINUTES=15
REQUEST_TIMEOUT_SECONDS=10
EOF
  chmod 600 .env
  echo "Wrote .env (HOST_URL=${HOST_URL})"
fi

# --- prereq: Tailscale socket mount, only if Tailscale is actually running ---
# A docker-compose.override.yml adds the mount conditionally, so `docker compose`
# never fails with "bind mount failed: /var/run/tailscale does not exist".
OVERRIDE="docker-compose.override.yml"
if [[ -S /var/run/tailscale/tailscaled.sock ]]; then
  cat > "${OVERRIDE}" <<'EOF'
# Auto-generated by install.sh: host runs Tailscale, so expose its socket.
services:
  devicemanager-client:
    volumes:
      - /var/run/tailscale:/var/run/tailscale:ro
EOF
  echo "Tailscale detected -> socket mount enabled via ${OVERRIDE}"
else
  rm -f "${OVERRIDE}"
  echo "No Tailscale socket here -> client will report 'No Tailscale client' (that's fine)."
fi

# --- prereq: optional in-browser SSH terminal ---
ENABLE_SSH="${ENABLE_SSH:-}"
if [[ -z "${ENABLE_SSH}" ]]; then
  read -rp "Authorize the dashboard's SSH key on this machine (for the in-browser terminal)? [y/N]: " ENABLE_SSH
fi
if [[ "${ENABLE_SSH}" =~ ^[Yy] ]]; then
  SSH_USER="${SSH_USER:-}"
  if [[ -z "${SSH_USER}" ]]; then
    read -rp "Local user to authorize [root]: " SSH_USER
  fi
  SSH_USER="${SSH_USER:-root}"
  if [[ "${EUID}" -ne 0 ]]; then
    echo "  SSH provisioning writes ${SSH_USER}'s authorized_keys and needs root."
    echo "  Run this once: sudo HOST_URL=${HOST_URL} SSH_USER=${SSH_USER} ./provision-ssh.sh"
  else
    HOST_URL="${HOST_URL}" SSH_USER="${SSH_USER}" bash "${SCRIPT_DIR}/provision-ssh.sh" || \
      echo "  SSH provisioning failed; re-run ./provision-ssh.sh later." >&2
  fi
fi

# --- start the client ---
echo
echo "Starting the client..."
docker compose up -d --build

echo
echo "Done. The client is running via docker compose."
echo "  Logs:    docker compose logs -f devicemanager-client"
echo "  Restart: docker compose restart devicemanager-client"
echo "  Stop:    docker compose down"
